# Generated by Django 2.1 on 2019-10-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat_name', models.CharField(max_length=30)),
                ('Chat_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_author_set', to=settings.AUTH_USER_MODEL)),
                ('Chat_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
